apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nbank-backend-monitor
  namespace: monitoring
  labels:
    app: nbank-backend
    release: monitoring
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      basicAuth:
        username:
          name: backend-basic-auth
          key: username
        password:
          name: backend-basic-auth
          key: password
---
apiVersion: v1
kind: Service
metadata:
  name: backend-metrics
  namespace: default
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 4111
      targetPort: 4111
      protocol: TCP
