name: Manual Build and Push new

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Docker tag (default: commit hash)"
        required: false
        default: ""
      test_profile:
        description: "Test profile (api/ui)"
        required: true
        default: "api"
        type: choice
        options:
          - api
          - ui

env:
  DOCKER_IMAGE_NAME: nbank-autotests
  DOCKER_REGISTRY: docker.io

jobs:
  manual-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build project
        run: mvn clean compile

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Run tests
        run: mvn test -P ${{ inputs.test_profile }}

      - name: Get commit hash
        id: commit-hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            TEST_PROFILE=${{ inputs.test_profile }}
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ inputs.docker_tag || steps.commit-hash.outputs.hash }}
            ${{ env.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
